### ISSUE TITLE
DB for developpment

### ISSUE THREAD

**Issue by aschwanb** [curtys/pse1#19]
Data collection will be running on main server. How do we access the database to test our code?

**Comment by aschwanb** [comment]
Nur DB auf Server verwenden.
Port Tunneling für die Anfragen, die normal auf die lokale DB gehen würden

**Comment by curtys** [comment]
Ein dump der Server-Datenbank ist wohl für lokale Entwicklung ausreichend.

**Comment by curtys** [comment]
Dump hochgeladen. Siehe readme für Instruktionen.
