### ISSUE TITLE
Check out code review

### ISSUE THREAD

**Issue by gianlucamateo** [curtys/pse1#29]
Pushed a .txt to a new branch. Please look it through and try to apply my suggestions. We can further discuss it on Friday after the customer meeting

**Comment by aschwanb** [comment]
Refactored everything but loops and return statements.
@curtys : I tested everything I could but please check again if the refactoring broke something. (We can always go back to a previous version)

**Comment by aschwanb** [comment]
Btw: Rubocop gibt es auch als plugin für RubyMine :+1: 
https://github.com/bbatsov/rubocop

**Comment by curtys** [comment]
Checked the code, everything ok.
